name: build

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: telescope-sample-debug.apk
          path: telescope-sample/build/outputs/apk/debug/telescope-sample-debug.apk
          if-no-files-found: error
